### PR TITLE
Fileupload

### PR DESCRIPTION
**Pull request by cgv2921**
This branch has been updated to merge with the lastest commit from master without issue.  The functionality we have done on this branch is all usable at this point.  Unfortunately, this does not include having loading a file go right into starting a game with that file.  The merging and refactoring process took longer than expected and there was no time left to work on writing the code to take the information from the uploaded file and start a game with it.

### CODE REVIEW

**Comment by ghost** [comment]
It doesn't look like you merged things correctly. I can't even run the application off the fileUpload branch. I think you need to pull the changes from master into your fileUpload branch and then create a pull request.

**Comment by cgv2921** [comment]
I can run it fine on my end.  If you'd looked at the commits just previously made you'd see that I just merged everything from master and then spent time fixing conflicts and refactoring.  If you are looking at this PR on github you can see that there are no conflicts with the master branch.  You may want to try to run clean build and then run build to see if that works.  Also you may not have the most recent version of the fileUpload branch.  Make sure you pulled from it recently.

**Comment by ghost** [comment]
I have checked out the latest from fileUpload, check out this screenshot.
screen shot 2017-04-26 at 2 42 08 am

**Comment by ghost** [comment]
Notice in AndroidManifest.xml the missing permissions. This is just one example showing things weren't merged correctly. It doesn't work on my end.

**Comment by jdh6660** [comment]
But now I notice the commit is off. You did commit more...

Wondering if it didn't make it back into fileUpload?

**Comment by ghost** [comment]
I just checked out 688f63912fc98a08b952775c050f7af919d4544d, your last commit to this pull request. And it's still not doing the merge completely/correctly. Check out the files changed tab and see things are missing.

**Comment by cgv2921** [comment]
Those permissions were deleted awhile back in fileUpload because they didn't really do much of anything, while the added permission allows us to read from files.  Maybe there is a feature that needs those permissions that I haven't noticed yet, but I haven't noticed anything that needs those permissions.  Those permissions might be needed in a way I didn't notice, but they definitely wouldn't affect your ability to build.  I checked all the files changed just now and found no issue.  Your issue with building might be coming from the local.properities file, which has been a nuisance on our branch.  We don't want it to be in our commits, but it is self generating upon builds and always seems to find a way into our commits.  If you change the sdk path in that to your own that may fix your issue.

**Comment by cgv2921** [comment]
I just threw in a commit that deletes local.properites.  Try it now and tell me about the build error if you still have one.

**Comment by cgv2921** [comment]
I pushed another commit.  This adds those permissions back because they might be needed in a feature the master branch has that I don't know about and don't affect the ability to build the project in any way.  Also I changed the build.gradle file to better match that on master in case that is affecting your build.  This involved downgrading to a past version of appcompat dependency.  The code should really only be additive at this point so there should be nothing stopping you from building the project on the fileUpload branch.

**Comment by cgv2921** [comment]
The issue you're having may be with the way that the word "HighScore" has been changed and refactored to "Highscore" on our branch.  If that seems to be the issue, let me know, it shouldn't be too hard to change that around.

**Comment by cgv2921** [comment]
Changed another build.gradle file to match the one on master.

**Comment by ghost** [comment]
So I'm able to compile and run the project. Can't select files on the Vuzix headset and the file chooser doesn't appear on my Nexus emulator. What are you experiencing?

**Comment by cgv2921** [comment]
The file choosing works fine on my emulator and I haven't had a chance yet to test it out with the Vuzix headset and as I haven't set it up to accept button commands like those the Vuzix would work with it's not surprising that you can't choose a file with it yet.

**Comment by cgv2921** [comment]
You can now use file upload given that the file being used is on the SD card and is called "mylocations.txt".  The ability to choose the file you want was put aside due to time constraints.  This is not yet been tested on the Vuzix device, only on the emulator where it was successful.  I will update this PR with the test results when that has been done.

**Review by ghost — APPROVED** [review]
Merging in file upload changes

**Pull request merged**
